### ISSUE TITLE
allow `values  = ` argument in `dhhs_colour|fill_manual`

### ISSUE THREAD

**Issue by wfmackey** [wfmackey/dhhstheme#5]
so that `dhhs_colour_manual(values = c(dhhs_teal, dhhs_pink))` works

**Comment by MattCowgill** [comment]
good idea @wfmackey

**Comment by wfmackey** [comment]
Done in [6524296](https://github.com/wfmackey/dhhstheme/commit/6524296a463d8ed8ab75fef1270f2ca4297200fd)
